
dependencies:
- base >= 4.7 && < 5
- postgresql-typed
- network
# - conduit
- text

haskell-solutions:
  source-dirs: src

executables:
  haskell-solutions:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
